blank_issues_enabled: false
contact_links:
  - name: Support and Questions
    url: https://github.community/
    about: https://github.com/JamesIves/github-pages-deploy-action/discussions/category_choices
