name: unit-tests
on:
  pull_request:
    branches:
      - dev
      - releases/v3
  push:
    branches:
      - dev
    tags-ignore:
      - '*.*'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install and Test
        run: |
          yarn install
          yarn lint
          yarn test

      - name: Uploade CodeCov Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
