name: unit
on:   
  push:	
    branches:	
      - master
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install and Test
      run: |
        npm install
        npm run-script test