name: integration-tests
on:
  schedule:
    - cron: 10 15 * * 0-6
  push:
    branches:
      - dev

  pull_request:
    branches:
      - releases/v3

jobs:
  integration-checkout-v1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: integration
          BASE_BRANCH: dev
          TARGET_FOLDER: montezuma

  integration-checkout-v2:
    needs: integration-checkout-v1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: integration
          BASE_BRANCH: dev
          TARGET_FOLDER: montezuma2

  integration-clean:
    needs: [integration-checkout-v1, integration-checkout-v2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: integration
          BASE_BRANCH: dev
          CLEAN: true

  integration-branch-creation:
    needs: [integration-checkout-v1, integration-checkout-v2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: integration-test-delete-test
          FOLDER: integration
          BASE_BRANCH: dev
          CLEAN: true

      - name: Cleanup Generated Branch
          run: |
            git push origin --delete integration-test-delete-test
